tunnel: "[tunnel-id]"
credentials-file: /Users/[username]/.cloudflared/[tunnel-id].json

ingress:
  - hostname: otp-client.your-domain.com
    service: http://localhost:3400
  - service: http_status:404
